spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_vue_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    #com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181